version: '3.8'
services:
  forge-server:
    build:
      context: .
      dockerfile: builder/Dockerfile
    volumes:
      - ./work:/app/work
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
